const KEY='travelBudgetData';
const CATS=[['Cibo'],['Alloggio'],['Trasporti'],['Attività'],['Extra']];
const PRE=[['Voli'],['Assicurazione'],['Vaccini'],['Attrezzatura'],['Visto'],['Altro pre-viaggio']];
const CURRENCIES=['EUR','THB','LAK','VND','KHR','USD','GBP','CHF','JPY','AUD','CAD','SGD','MYR','IDR','PHP','INR','CNY','KRW','TRY','AED','BRL','NZD','ZAR','MXN','COP','PEN','CLP','BOB','MAD','EGP','KES','TZS','GHS','NGN','BDT','NPR','PKR','LKR','TWD','HKD','MOP','MMK','BND','FJD','PGK','Altra valuta'];
const CURRENCY_FLAGS={EUR:'🇪🇺',THB:'🇹🇭',LAK:'🇱🇦',VND:'🇻🇳',KHR:'🇰🇭',USD:'🇺🇸',GBP:'🇬🇧',CHF:'🇨🇭',JPY:'🇯🇵',AUD:'🇦🇺',CAD:'🇨🇦',SGD:'🇸🇬',MYR:'🇲🇾',IDR:'🇮🇩',PHP:'🇵🇭',INR:'🇮🇳',CNY:'🇨🇳',KRW:'🇰🇷',TRY:'🇹🇷',AED:'🇦🇪',BRL:'🇧🇷',NZD:'🇳🇿',ZAR:'🇿🇦',MXN:'🇲🇽',COP:'🇨🇴',PEN:'🇵🇪',CLP:'🇨🇱',BOB:'🇧🇴',MAD:'🇲🇦',EGP:'🇪🇬',KES:'🇰🇪',TZS:'🇹🇿',GHS:'🇬🇭',NGN:'🇳🇬',BDT:'🇧🇩',NPR:'🇳🇵',PKR:'🇵🇰',LKR:'🇱🇰',TWD:'🇹🇼',HKD:'🇭🇰',MOP:'🇲🇴',MMK:'🇲🇲',BND:'🇧🇳',FJD:'🇫🇯',PGK:'🇵🇬'};
const WALLET_TYPES=['Carta','Contanti','Conto','Personalizzato'];
const CURRENCY_NAMES={EUR:'Euro',THB:'Baht thailandese',LAK:'Kip laotiano',VND:'Dong vietnamita',KHR:'Riel cambogiano',USD:'Dollaro statunitense',GBP:'Sterlina britannica',CHF:'Franco svizzero',JPY:'Yen giapponese',AUD:'Dollaro australiano',CAD:'Dollaro canadese',SGD:'Dollaro di Singapore',MYR:'Ringgit malese',IDR:'Rupia indonesiana',PHP:'Peso filippino',INR:'Rupia indiana',CNY:'Yuan cinese',KRW:'Won sudcoreano',TRY:'Lira turca',AED:'Dirham degli Emirati',BRL:'Real brasiliano',NZD:'Dollaro neozelandese',ZAR:'Rand sudafricano',MXN:'Peso messicano',COP:'Peso colombiano',PEN:'Sol peruviano',CLP:'Peso cileno',BOB:'Boliviano',MAD:'Dirham marocchino',EGP:'Sterlina egiziana',KES:'Scellino keniota',TZS:'Scellino tanzaniano',GHS:'Cedi ghanese',NGN:'Naira nigeriana',BDT:'Taka bengalese',NPR:'Rupia nepalese',PKR:'Rupia pakistana',LKR:'Rupia singalese',TWD:'Dollaro taiwanese',HKD:'Dollaro di Hong Kong',MOP:'Pataca di Macao',MMK:'Kyat birmano',BND:'Dollaro del Brunei',FJD:'Dollaro figiano',PGK:'Kina della Papua Nuova Guinea'};
const NAV=[['Dashboard','dashboard'],['Giorni','daysPage'],['Statistiche','statistics'],['Portafogli','wallets'],['Movimenti','movements'],['Impostazioni','settings']];
let data=JSON.parse(localStorage.getItem(KEY)||'null')||{trips:[],active:null};
let currentPage='dashboard', returnPage='dashboard';
function id(){return crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2)}
function save(){localStorage.setItem(KEY,JSON.stringify(data))}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function trip(){return data.trips.find(t=>t.id===data.active)}
function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function dateObj(s){const [y,m,d]=(s||today()).split('-').map(Number);return new Date(y,m-1,d)}
function isoDate(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function fmtDate(s){if(!s)return '—';const [y,m,d]=s.split('-');return `${d}-${m}-${y}`}
function effectiveToday(t){return t?.testMode&&t.testDate?t.testDate:today()}
function elapsed(t){if(!t?.start)return 0;const a=dateObj(t.start),b=dateObj(effectiveToday(t));if(b<a)return 0;return Math.floor((b-a)/86400000)+1}
function currencySymbol(c){return ({EUR:'€',USD:'$',GBP:'£',CHF:'CHF',THB:'฿',JPY:'¥',CNY:'¥',KRW:'₩',INR:'₹'})[c]||c}
function money(n,c='EUR'){return new Intl.NumberFormat('it-IT',{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(n)||0)+' '+currencySymbol(c)}
function moneyShort(n,c){return new Intl.NumberFormat('it-IT',{style:'currency',currency:c==='EUR'?'EUR':'EUR'}).format(Number(n)||0).replace('€','€')}
function num(n){return new Intl.NumberFormat('it-IT',{maximumFractionDigits:2}).format(Number(n)||0)}
function catEmoji(c){return ''}
function walletById(t,wid){return t.wallets.find(w=>w.id===wid)||t.wallets.find(w=>w.name===wid)}
function migrate(){
 data.trips=(data.trips||[]).map(t=>{
  t.id=t.id||id(); t.name=t.name||'Nuovo viaggio'; t.baseCurrency=(t.baseCurrency||t.currency||'EUR').toUpperCase();
  t.budget=Number(t.budget??t.totalBudgetEUR??0); t.daily=Number(t.daily??t.dailyBudgetEUR??0); t.start=t.start||t.startDate||today(); t.duration=Number(t.duration||0);
  t.movements=t.movements||t.transactions||[]; t.preTrip=t.preTrip||[]; t.testMode=!!t.testMode; t.testDate=t.testDate||t.start; t.wallets=t.wallets||[];
  t.wallets.forEach(w=>{w.id=w.id||id();w.name=w.name||'Portafoglio';w.currency=(w.currency||'EUR').toUpperCase();w.emoji='';w.type=w.type||'Personalizzato';w.openingBalance=Number(w.openingBalance??w.balance??0);w.balance=Number(w.balance??w.openingBalance);});
  t.movements=t.movements.map(m=>({id:m.id||id(),type:m.type||'expense',label:m.label||m.description||'Movimento',category:m.category||'Extra',paymentDate:m.paymentDate||m.date||today(),activityDate:m.activityDate||'',wallet:m.wallet||'',walletFrom:m.walletFrom||m.wallet||'',walletTo:m.walletTo||'',local:Number(m.local??m.localAmount??0),currency:(m.currency||m.localCurrency||'EUR').toUpperCase(),eur:Number(m.eur??m.eurAmount??0),budgetValue:Number(m.budgetValue??m.eur??0),walletAmount:Number(m.walletAmount??m.local??m.eur??0),fromAmount:Number(m.fromAmount||0),toAmount:Number(m.toAmount||0),inBudget:m.inBudget!==false}));
  t.preTrip=t.preTrip.map(m=>({...m,id:m.id||id(),eur:Number(m.eur||0),local:Number(m.local||0),currency:(m.currency||'EUR').toUpperCase()})); return t;
 });
}
migrate();save();
function recalc(t){t.wallets.forEach(w=>w.balance=Number(w.openingBalance||0));t.movements.forEach(m=>{if(m.type==='expense'){const w=walletById(t,m.walletFrom||m.wallet);if(w)w.balance-=Number(m.walletAmount||0)}else if(m.type==='transfer'){const a=walletById(t,m.walletFrom),b=walletById(t,m.walletTo);if(a)a.balance-=Number(m.fromAmount||0);if(b)b.balance+=Number(m.toAmount||0)}})}
function budgetSpent(t){return t.movements.filter(m=>m.type==='expense'&&m.inBudget!==false).reduce((a,m)=>a+Number(m.budgetValue??m.eur??0),0)}
function daySpent(t,d){return t.movements.filter(m=>m.type==='expense'&&m.inBudget!==false&&m.paymentDate===d).reduce((a,m)=>a+Number(m.budgetValue??m.eur??0),0)}
function preTotal(t){return t.preTrip.reduce((a,m)=>a+Number(m.eur||0),0)}
function stats(t){const spent=budgetSpent(t),d=elapsed(t),day=effectiveToday(t),todaySpent=daySpent(t,day),avg=d?spent/d:0,cum=t.daily*d;return{spent,pre:preTotal(t),remaining:t.budget-spent,daily:t.daily,todaySpent,avg,cumTarget:cum,margin:cum-spent,d,day}}
function fmtBudget(t,n){return money(n,t.baseCurrency)}
function walletEquivalent(w,t){if(w.currency===t.baseCurrency)return null;const rates=[];t.movements.forEach(m=>{if(m.type==='expense'&&m.walletFrom===w.id&&m.currency===w.currency&&m.local>0&&m.budgetValue>0)rates.push(m.budgetValue/m.local);});if(!rates.length)return null;return w.balance*(rates.reduce((a,b)=>a+b,0)/rates.length)}
function layout(body,active=currentPage){currentPage=active;document.getElementById('app').innerHTML=`<main class="shell">${body}</main>${nav(active)}`}
function nav(active){return `<nav class="nav">${NAV.map(([l,fn])=>`<button class="${active===fn?'active':''}" onclick="${fn}()"><small>${l}</small></button>`).join('')}</nav>`}
function home(){document.getElementById('app').innerHTML=`<main class="shell"><div class="top"><div><div class="title">I miei viaggi</div><div class="sub">Budget offline · dati solo sul dispositivo</div></div></div><div class="card"><button class="btn full" onclick="newTrip()">＋ Nuovo viaggio</button></div>${data.trips.length?`<div class="list">${data.trips.map(t=>`<button class="card tripcard" onclick="openTrip('${t.id}')"><b>${esc(t.name)}</b><span>${fmtDate(t.start)} · ${fmtBudget(t,t.budget)}</span></button>`).join('')}</div>`:'<div class="empty">Nessun viaggio creato.</div>'}</main>`}
function dashboard(){const t=trip();if(!t)return home();recalc(t);save();const s=stats(t),remDay=t.daily-s.todaySpent;const over=s.todaySpent>t.daily,avgOver=s.avg>t.daily,marginNeg=s.margin<0;layout(`<div class="top"><div><div class="sub">VIAGGIO ${t.testMode?`<span class="testpill">Test · ${fmtDate(s.day)}</span>`:''}</div><div class="title">${esc(t.name)}</div></div><button class="back" onclick="home()">Viaggi</button></div><div class="card hero"><div class="label">Budget viaggio rimanente</div><div class="big">${fmtBudget(t,s.remaining)}</div><div class="muted light">Speso ${fmtBudget(t,s.spent)} di ${fmtBudget(t,t.budget)}</div></div><div class="grid"><div class="stat ${over?'warn':''}"><span class="label">Spesi oggi</span><b>${fmtBudget(t,s.todaySpent)}</b><small>${remDay>=0?'Rimangono '+fmtBudget(t,remDay):'Sopra budget di '+fmtBudget(t,-remDay)}</small></div><div class="stat"><span class="label">Budget giornaliero</span><b>${fmtBudget(t,t.daily)} / giorno</b><small>Budget impostato · Giorno ${s.d||'—'}</small></div><div class="stat ${avgOver?'warn':''}"><span class="label">Media giornaliera</span><b>${fmtBudget(t,s.avg)}</b><small>${s.d?'Calcolata sui giorni trascorsi':'Il viaggio non è ancora iniziato'}</small></div><div class="stat ${marginNeg?'warn':''}"><span class="label">Margine cumulativo</span><b>${s.margin>=0?'+':''}${fmtBudget(t,s.margin)}</b><small>${s.margin>=0?'speso '+fmtBudget(t,s.margin)+' in meno del previsto':'speso '+fmtBudget(t,-s.margin)+' in più del previsto'}</small></div></div><div class="row dashboard-actions"><button class="btn" onclick="addExpense()">＋ Spesa</button><button class="btn secondary" onclick="withdrawal()">⇄ Cambio</button></div><div class="card"><div class="sectionhead"><b>Portafogli</b><button class="link" onclick="wallets()">Gestisci</button></div>${walletsMini(t)}</div><div class="card"><div class="sectionhead"><b>Ultimi movimenti</b><button class="link" onclick="movements()">Tutti</button></div>${recent(t)}</div>`,'dashboard')}
function walletsMini(t){return t.wallets.length?`<div class="list">${t.wallets.map(w=>walletLine(t,w)).join('')}</div>`:'<div class="empty">Nessun portafoglio</div>'}
function walletLine(t,w){const eq=walletEquivalent(w,t);return `<div class="item"><div><div class="cat">${esc(w.name)}</div><div class="muted">${esc(w.currency)}${eq!==null?' · ≈ '+fmtBudget(t,eq):''}</div></div><div class="amount">${num(w.balance)} ${esc(w.currency)}</div></div>`}
function recent(t){const ms=[...t.movements].sort((a,b)=>b.paymentDate.localeCompare(a.paymentDate)).slice(0,5);return ms.length?`<div class="list">${ms.map(m=>movementHTML(t,m)).join('')}</div>`:'<div class="empty">Nessun movimento</div>'}
function movementHTML(t,m){if(m.type==='transfer'){const a=walletById(t,m.walletFrom),b=walletById(t,m.walletTo);return `<div class="item"><div><div class="cat">${esc(m.label)}</div><div class="muted">${esc(a?.name||'')} → ${esc(b?.name||'')}</div><div class="secondaryline">${fmtDate(m.paymentDate)} · − ${num(m.fromAmount)} ${esc(a?.currency||'')} → + ${num(m.toAmount)} ${esc(b?.currency||'')}</div></div><div class="actions"><button onclick="editMovement('${m.id}')">✎</button><button onclick="deleteMovement('${m.id}')">×</button></div></div>`}const w=walletById(t,m.walletFrom||m.wallet);return `<div class="item"><div><div class="cat">${esc(w?.name||m.wallet||'Portafoglio')}</div><div class="muted">${fmtDate(m.paymentDate)} · ${num(m.local||m.walletAmount)} ${esc(m.currency)}</div><div class="secondaryline">${esc(m.category)} · ${esc(m.label)}${m.currency!==t.baseCurrency?' · '+fmtBudget(t,m.budgetValue):''}</div></div><div class="actions"><button onclick="editMovement('${m.id}')">✎</button><button onclick="deleteMovement('${m.id}')">×</button></div></div>`}
function currencyOptions(selected){return CURRENCIES.map(c=>`<option value="${c==='Altra valuta'?'':c}" ${selected===c?'selected':''}>${c==='Altra valuta'?'Altra valuta':`${CURRENCY_FLAGS[c]||''} ${c} — ${CURRENCY_NAMES[c]||c}`}</option>`).join('')}
function newTrip(){document.getElementById('app').innerHTML=`<main class="shell"><button class="back" onclick="home()">← Indietro</button><h1>Nuovo viaggio</h1><div class="card"><div class="field"><label>Nome viaggio</label><input id="name" placeholder="Sud Est Asiatico"></div><div class="field"><label>Valuta del budget</label><select id="base">${currencyOptions('EUR')}</select></div><div class="field"><label>Budget totale</label><input id="budget" inputmode="decimal" type="text" min="0" step="0.01" value="6000"></div><div class="field"><label>Budget giornaliero</label><input id="daily" inputmode="decimal" type="text" min="0" step="0.01" value="35"></div><div class="field"><label>Data di inizio</label><input id="start" type="date" value="${today()}"></div><button class="btn full" onclick="createTrip()">Crea viaggio</button></div></main>`}
function createTrip(){const base=document.getElementById('base').value||prompt('Inserisci il codice valuta, es. NOK')?.toUpperCase()||'EUR',budget=Math.max(0,parseAmount(document.getElementById('budget').value)),daily=Math.max(0,parseAmount(document.getElementById('daily').value));const t={id:id(),name:document.getElementById('name').value.trim()||'Nuovo viaggio',baseCurrency:base,budget,daily,start:document.getElementById('start').value||today(),duration:0,movements:[],preTrip:[],wallets:[],testMode:false,testDate:''};data.trips.push(t);data.active=t.id;save();walletForm(null,'dashboard')}
function openTrip(i){data.active=i;save();dashboard()}
function addExpense(){expenseForm(null,false,'dashboard')}
function expenseForm(m=null,pre=false,back='dashboard'){const t=trip(),editing=!!m,wallet=walletById(t,m?.walletFrom||m?.wallet),vals=m||{label:'',category:pre?'Voli':'Cibo',walletFrom:t.lastWalletId||t.wallets[0]?.id||'',local:'',currency:t.wallets[0]?.currency||t.baseCurrency,budgetValue:'',paymentDate:effectiveToday(t),activityDate:''};const w=wallet||t.wallets[0];const currency=w?.currency||vals.currency||t.baseCurrency;document.getElementById('app').innerHTML=`<main class="shell"><button class="back" onclick="${back}()">← Indietro</button><h1>${editing?'Modifica':'Aggiungi'} ${pre?'spesa pre-viaggio':'spesa'}</h1><div class="card"><div class="field"><label>Descrizione</label><input id="label" value="${esc(vals.label)}" placeholder="Cena, bus, ostello..."></div><div class="field"><label>Categoria</label><select id="cat">${(pre?PRE:CATS).map(x=>`<option value="${x[0]}" ${x[0]===vals.category?'selected':''}>${x[0]}</option>`).join('')}</select></div>${!pre?`<div class="field"><label>Portafoglio</label><select id="wallet" onchange="syncExpenseCurrency()">${t.wallets.map(x=>`<option value="${x.id}" ${x.id===(vals.walletFrom||'')?'selected':''}>${esc(x.name)} · ${esc(x.currency)}</option>`).join('')}</select></div>`:''}<div id="amountFields">${expenseAmountFields(t,vals,currency,pre)}</div><div class="field"><label>Data pagamento</label><input id="date" type="date" value="${esc(vals.paymentDate||effectiveToday(t))}"></div><div class="field"><label>Data attività (opzionale)</label><input id="activity" type="date" value="${esc(vals.activityDate||'')}"></div><button class="btn full" onclick="saveExpense(${m?`'${m.id}'`:'null'},${pre},'${back}')">Salva</button></div></main>`}
function expenseAmountFields(t,vals,currency,pre){if(pre)return `<div class="field"><label>Importo</label><div class="inlineAmount"><input id="local" inputmode="decimal" type="text" min="0" step="0.01" value="${vals.local??''}"><span>${esc(vals.currency||t.baseCurrency)}</span></div></div><div class="field"><label>Valore in ${esc(t.baseCurrency)} *</label><input id="budgetValue" inputmode="decimal" type="text" min="0" step="0.01" value="${vals.budgetValue??vals.eur??''}"></div>`;const w=walletById(t,vals.walletFrom)||t.wallets[0];if(!w)return '<div class="hint">Prima crea un portafoglio.</div>';if(w.currency===t.baseCurrency)return `<div class="field"><label>Importo</label><div class="inlineAmount"><input id="local" inputmode="decimal" type="text" min="0" step="0.01" value="${vals.local??vals.walletAmount??''}"><span>${esc(w.currency)}</span></div><input id="budgetValue" type="hidden" value="${vals.budgetValue??vals.eur??vals.local??''}"></div>`;return `<div class="field"><label>Importo</label><div class="inlineAmount"><input id="local" inputmode="decimal" type="text" min="0" step="0.01" value="${vals.local??''}"><span>${esc(w.currency)}</span></div></div><div class="field"><label>Valore in ${esc(t.baseCurrency)} *</label><input id="budgetValue" inputmode="decimal" type="text" min="0" step="0.01" value="${vals.budgetValue??vals.eur??''}"></div>`}
function syncExpenseCurrency(){const t=trip(),wid=document.getElementById('wallet').value,w=walletById(t,wid),current={label:document.getElementById('label').value,category:document.getElementById('cat').value,walletFrom:wid,local:document.getElementById('local')?.value||'',budgetValue:document.getElementById('budgetValue')?.value||'',paymentDate:document.getElementById('date').value,activityDate:document.getElementById('activity').value};document.getElementById('amountFields').innerHTML=expenseAmountFields(t,current,w.currency,false)}
function parseAmount(v){if(typeof v==='number')return Number.isFinite(v)?v:0;const s=String(v??'').trim().replace(/\s/g,'').replace(',','.');const n=Number(s);return Number.isFinite(n)?n:0}
function saveExpense(mid,pre,back){const t=trip(),label=document.getElementById('label').value.trim()||document.getElementById('cat').value,category=document.getElementById('cat').value,paymentDate=document.getElementById('date').value||effectiveToday(t),activityDate=document.getElementById('activity').value||'';if(pre){const local=parseAmount(document.getElementById('local')?.value),budgetValue=parseAmount(document.getElementById('budgetValue')?.value);if(local<=0||budgetValue<=0)return alert(`Inserisci importo e valore in ${t.baseCurrency}.`);const m=mid?t.preTrip.find(x=>x.id===mid):null,obj={id:mid||id(),label,category,local,currency:t.baseCurrency,eur:budgetValue,paymentDate,activityDate};if(m)Object.assign(m,obj);else t.preTrip.push(obj);save();renderCurrent(back);return}const wid=document.getElementById('wallet')?.value,w=walletById(t,wid);if(!w)return alert('Crea prima un portafoglio.');let local=parseAmount(document.getElementById('local')?.value),budgetValue=parseAmount(document.getElementById('budgetValue')?.value);if(w.currency===t.baseCurrency){if(local<=0)return alert(`Inserisci l'importo in ${t.baseCurrency}.`);budgetValue=local}else if(w.type==='Carta'){if(budgetValue<=0)return alert(`Inserisci il valore in ${t.baseCurrency}.`);if(local<0)local=0}else{if(local<=0||budgetValue<=0)return alert(`Inserisci importo e valore in ${t.baseCurrency}.`)}const walletAmount=w.currency===t.baseCurrency?budgetValue:local;recalc(t);const old=mid?t.movements.find(x=>x.id===mid):null;const available=Number(w.balance||0)+(old&&old.type==='expense'&&old.walletFrom===w.id?Number(old.walletAmount||0):0);if(walletAmount>available+0.000001)return alert(`Saldo insufficiente in ${w.name}. Disponibili ${money(available,w.currency)}.`);const m=old||{id:mid||id()};const obj={id:mid||m.id,type:'expense',label,category,wallet:w.name,walletFrom:w.id,local,currency:w.currency,budgetValue,eur:t.baseCurrency==='EUR'?budgetValue:0,walletAmount,paymentDate,activityDate,inBudget:true};Object.assign(m,obj);if(!old)t.movements.push(m);t.lastWalletId=w.id;recalc(t);save();renderCurrent(back)}
function renderCurrent(page=currentPage){if(page==='dashboard')dashboard();else if(page==='daysPage')daysPage();else if(page==='statistics')statistics();else if(page==='wallets')wallets();else if(page==='movements')movements();else if(page==='settings')settings();else dashboard()}
function editMovement(mid){const t=trip(),m=t.movements.find(x=>x.id===mid);if(!m)return;returnPage=currentPage;if(m.type==='transfer')transferForm(m,currentPage);else expenseForm(m,false,currentPage)}
function deleteMovement(mid){const t=trip();if(!confirm('Eliminare questo movimento?'))return;t.movements=t.movements.filter(m=>m.id!==mid);recalc(t);save();renderCurrent(currentPage)}
function withdrawal(){transferForm(null,currentPage)}
function transferForm(m=null,back='dashboard'){const t=trip();const from=m?.walletFrom||t.lastFromWalletId||t.wallets[0]?.id||'',to=m?.walletTo||t.lastToWalletId||t.wallets.find(w=>w.id!==from)?.id||t.wallets[0]?.id||'';document.getElementById('app').innerHTML=`<main class="shell"><button class="back" onclick="${back}()">← Indietro</button><h1>${m?'Modifica cambio':'Cambio'}</h1><div class="card"><div class="transfer-side"><div class="field"><label>Portafoglio di uscita</label><select id="from" onchange="syncTransferLabels()">${t.wallets.map(w=>`<option value="${w.id}" ${w.id===from?'selected':''}>${esc(w.name)}</option>`).join('')}</select></div><div class="field"><label id="fromLabel">Importo</label><div class="inlineAmount"><input id="fromAmount" inputmode="decimal" type="text" value="${m?.fromAmount??''}"><span id="fromCurrency">${esc(walletById(t,from)?.currency||'')}</span></div></div></div><div class="transfer-arrow">⇄</div><div class="transfer-side"><div class="field"><label>Portafoglio di entrata</label><select id="to" onchange="syncTransferLabels()">${t.wallets.map(w=>`<option value="${w.id}" ${w.id===to?'selected':''}>${esc(w.name)}</option>`).join('')}</select></div><div class="field"><label id="toLabel">Importo ricevuto</label><div class="inlineAmount"><input id="toAmount" inputmode="decimal" type="text" value="${m?.toAmount??''}"><span id="toCurrency">${esc(walletById(t,to)?.currency||'')}</span></div></div></div><div class="field"><label>Totale pagato</label><div class="inlineAmount"><input id="cost" inputmode="decimal" type="text" value="${m?.eur??''}"><span>${esc(t.baseCurrency)}</span></div></div><p class="hint">Il totale pagato è quanto è uscito dal portafoglio di uscita, comprensivo di eventuali commissioni. La commissione viene calcolata automaticamente quando il valore trasferito e il totale pagato sono confrontabili in ${esc(t.baseCurrency)}.</p><div class="field"><label>Data pagamento</label><input id="date" type="date" value="${m?.paymentDate||effectiveToday(t)}"></div><button class="btn full" onclick="saveTransfer(${m?`'${m.id}'`:'null'},'${back}')">Salva</button></div></main>`} 
function syncTransferLabels(){const t=trip(),a=walletById(t,document.getElementById('from').value),b=walletById(t,document.getElementById('to').value);document.getElementById('fromCurrency').textContent=a?.currency||'';document.getElementById('toCurrency').textContent=b?.currency||'';document.getElementById('fromLabel').textContent=`Importo da ${a?.currency||''}`;document.getElementById('toLabel').textContent=`Importo a ${b?.currency||''}`}
function saveTransfer(mid,back){const t=trip(),a=document.getElementById('from').value,b=document.getElementById('to').value,fromAmount=parseAmount(document.getElementById('fromAmount').value),toAmount=parseAmount(document.getElementById('toAmount').value),cost=parseAmount(document.getElementById('cost').value);if(a===b)return alert('Il portafoglio di uscita e quello di entrata devono essere diversi.');if(fromAmount<=0||toAmount<=0||cost<=0)return alert('Completa i dati del cambio.');const wa=walletById(t,a),wb=walletById(t,b);if(!wa||!wb)return alert('Portafoglio non valido.');const old=mid?t.movements.find(x=>x.id===mid):null;recalc(t);const available=Number(wa.balance||0)+(old&&old.type==='transfer'&&old.walletFrom===a?Number(old.fromAmount||0):0);if(fromAmount>available+0.000001)return alert(`Saldo insufficiente in ${wa.name}. Disponibili ${money(available,wa.currency)}.`);const m=old||{id:mid||id()};Object.assign(m,{id:mid||m.id,type:'transfer',label:`${wa.currency} → ${wb.currency}`,wallet:wa.name,walletFrom:a,walletTo:b,fromAmount,toAmount,eur:cost,budgetValue:0,local:toAmount,currency:wb.currency,paymentDate:document.getElementById('date').value||effectiveToday(t),inBudget:false});if(!old)t.movements.push(m);t.lastFromWalletId=a;t.lastToWalletId=b;recalc(t);save();renderCurrent(back)}
function wallets(){const t=trip();recalc(t);save();layout(`<div class="top"><div><div class="sub">VIAGGIO</div><div class="title">Portafogli</div></div></div><div class="card">${t.wallets.length?t.wallets.map(w=>`<div class="item walletitem"><div><div class="cat">${esc(w.name)}</div><div class="muted">${esc(w.type)} · ${esc(w.currency)}${walletEquivalent(w,t)!==null?' · ≈ '+fmtBudget(t,walletEquivalent(w,t)):''}</div></div><div class="actions"><div class="amount">${num(w.balance)} ${esc(w.currency)}</div><button onclick="editWallet('${w.id}')">✎</button><button onclick="deleteWallet('${w.id}')">×</button></div></div>`).join(''):'<div class="empty">Nessun portafoglio</div>'}</div><button class="btn full" onclick="walletForm(null,'wallets')">＋ Aggiungi portafoglio</button>`,'wallets')}
function walletForm(existing=null,back='wallets'){const t=trip(),w=existing||{name:'',type:'Carta',currency:t.baseCurrency,openingBalance:0};const customType=w.type&&!WALLET_TYPES.includes(w.type)?w.type:'';const customCurrency=w.currency&&!CURRENCIES.includes(w.currency)?w.currency:'';const typeValue=customType?'Personalizzato':w.type;const currencyValue=customCurrency?'':w.currency;document.getElementById('app').innerHTML=`<main class="shell"><button class="back" onclick="${back}()">← Indietro</button><h1>${existing?'Modifica':'Nuovo'} portafoglio</h1><div class="card"><div class="field"><label>Nome</label><input id="wname" value="${esc(w.name)}" placeholder="Revolut, Contanti Thailandia..."></div><div class="field"><label>Tipo</label><select id="wtype" onchange="syncWalletCustomFields()">${WALLET_TYPES.map(x=>`<option value="${x}" ${x===typeValue?'selected':''}>${x}</option>`).join('')}</select></div><div id="customTypeWrap" class="field" style="${typeValue==='Personalizzato'?'':'display:none'}"><label>Tipo personalizzato</label><input id="wcustomtype" value="${esc(customType)}" placeholder="Es. PayPal"></div><div class="field"><label>Valuta</label><select id="wcur" onchange="syncWalletCustomFields()">${currencyOptions(currencyValue||w.currency)}</select></div><div id="customCurrencyWrap" class="field" style="${!currencyValue?'':'display:none'}"><label>Valuta personalizzata</label><input id="wcustomcur" value="${esc(customCurrency)}" placeholder="Es. XOF"></div>${!existing?`<div class="field"><label>Saldo iniziale</label><input id="wopening" inputmode="decimal" type="text" value="0"></div>`:''}<button class="btn full" onclick="saveWallet(${existing?`'${existing.id}'`:'null'},'${back}')">Salva</button></div></main>`} 
function syncWalletCustomFields(){const type=document.getElementById('wtype').value,cur=document.getElementById('wcur').value;document.getElementById('customTypeWrap').style.display=type==='Personalizzato'?'':'none';document.getElementById('customCurrencyWrap').style.display=cur===''?'':'none'}
function addWallet(){walletForm(null,'wallets')}
function saveWallet(wid,back){const t=trip(),name=document.getElementById('wname').value.trim();if(!name)return alert('Inserisci un nome.');const typeBase=document.getElementById('wtype').value,type=typeBase==='Personalizzato'?(document.getElementById('wcustomtype').value.trim()||'Personalizzato'):typeBase;const curBase=document.getElementById('wcur').value,cur=(curBase||document.getElementById('wcustomcur').value.trim()).toUpperCase();if(!cur)return alert('Inserisci la valuta.');if(wid){const w=walletById(t,wid);w.name=name;w.currency=cur;w.type=type;t.movements.forEach(m=>{if(m.walletFrom===w.id)m.wallet=w.name})}else{const opening=Math.max(0,parseAmount(document.getElementById('wopening').value));t.wallets.push({id:id(),name,type,currency:cur,openingBalance:opening,balance:opening})}recalc(t);save();renderCurrent(back)}
function editWallet(wid){const t=trip(),w=walletById(t,wid);if(w)walletForm(w,'wallets')}
function deleteWallet(wid){const t=trip(),w=walletById(t,wid);if(!w)return;const linked=t.movements.some(m=>m.walletFrom===w.id||m.walletTo===w.id);if(Math.abs(w.balance)>0.005||linked)return alert('Puoi eliminare il portafoglio solo se il saldo è zero e non ha movimenti collegati.');if(!confirm(`Eliminare ${w.name}?`))return;t.wallets=t.wallets.filter(x=>x.id!==w.id);save();renderCurrent('wallets')}
function movements(){const t=trip();layout(`<div class="top"><div><div class="sub">VIAGGIO</div><div class="title">Movimenti</div></div></div><div class="row"><button class="btn" onclick="addExpense()">＋ Spesa</button><button class="btn secondary" onclick="withdrawal()">⇄ Cambio</button></div><div class="card"><div class="filters"><input id="search" placeholder="Cerca descrizione, portafoglio..." oninput="renderMovementList()"><select id="filterCat" onchange="renderMovementList()"><option value="">Tutte le categorie</option>${CATS.map(x=>`<option>${x[0]}</option>`).join('')}</select><select id="filterType" onchange="renderMovementList()"><option value="">Tutti i tipi</option><option value="expense">Spese</option><option value="transfer">Cambi</option></select><select id="filterWallet" onchange="renderMovementList()"><option value="">Tutti i portafogli</option>${t.wallets.map(w=>`<option value="${w.id}">${esc(w.name)}</option>`).join('')}</select><select id="filterCurrency" onchange="renderMovementList()"><option value="">Tutte le valute</option>${[...new Set(t.wallets.map(w=>w.currency))].map(c=>`<option value="${c}">${esc(c)}</option>`).join('')}</select><select id="filterPeriod" onchange="renderMovementList()"><option value="">Tutto il periodo</option><option value="7">Ultimi 7 giorni</option><option value="30">Ultimi 30 giorni</option></select><select id="filterSort" onchange="renderMovementList()"><option value="newest">Più recenti</option><option value="oldest">Più vecchi</option></select></div><div id="movementList"></div></div><div class="card"><div class="sectionhead"><b>Spese pre-viaggio</b><button class="link" onclick="preExpense()">＋ Aggiungi</button></div>${preList(t)}</div>`,'movements');renderMovementList()}
function renderMovementList(){const t=trip(),q=(document.getElementById('search')?.value||'').toLowerCase(),cat=document.getElementById('filterCat')?.value||'',type=document.getElementById('filterType')?.value||'',wid=document.getElementById('filterWallet')?.value||'',cur=document.getElementById('filterCurrency')?.value||'',period=Number(document.getElementById('filterPeriod')?.value||0),sort=document.getElementById('filterSort')?.value||'newest',todayD=dateObj(effectiveToday(t)),cut=period?new Date(todayD.getFullYear(),todayD.getMonth(),todayD.getDate()-period+1):null;let ms=[...t.movements].filter(m=>(!q||`${m.label} ${m.category} ${m.currency} ${m.wallet}`.toLowerCase().includes(q))&&(!cat||m.category===cat)&&(!type||m.type===type)&&(!wid||m.walletFrom===wid||m.walletTo===wid)&&(!cur||m.currency===cur||(walletById(t,m.walletFrom)?.currency===cur)||(walletById(t,m.walletTo)?.currency===cur))&&(!cut||dateObj(m.paymentDate)>=cut));ms.sort((a,b)=>sort==='oldest'?a.paymentDate.localeCompare(b.paymentDate):b.paymentDate.localeCompare(a.paymentDate));document.getElementById('movementList').innerHTML=ms.length?`<div class="list">${ms.map(m=>movementHTML(t,m)).join('')}</div>`:'<div class="empty">Nessun movimento trovato</div>'}
function preList(t){return t.preTrip.length?`<div class="list">${[...t.preTrip].sort((a,b)=>b.paymentDate.localeCompare(a.paymentDate)).map(m=>`<div class="item"><div><div class="cat">${esc(m.label)}</div><div class="muted">${fmtDate(m.paymentDate)} · ${num(m.local)} ${esc(m.currency)} · ${fmtBudget(t,m.eur)}</div></div><div class="actions"><button onclick="editPre('${m.id}')">✎</button><button onclick="deletePre('${m.id}')">×</button></div></div>`).join('')}</div>`:'<div class="empty">Nessuna spesa pre-viaggio</div>'}
function preExpense(){expenseForm(null,true,'movements')}
function editPre(pid){const t=trip(),m=t.preTrip.find(x=>x.id===pid);if(m)expenseForm({...m, walletFrom:t.wallets[0]?.id||''},true,'movements')}
function deletePre(pid){const t=trip();if(!confirm('Eliminare questa spesa pre-viaggio?'))return;t.preTrip=t.preTrip.filter(m=>m.id!==pid);save();renderCurrent('movements')}
function dayList(t){const n=Math.max(t.duration||0,elapsed(t),1);return Array.from({length:n},(_,i)=>{const d=dateObj(t.start);d.setDate(d.getDate()+i);return isoDate(d)})}
function daysPage(){const t=trip(),s=stats(t);layout(`<div class="top"><div><div class="sub">VIAGGIO</div><div class="title">Giorni</div></div></div><div class="card"><b>${s.d?s.d+' giorni trascorsi':'Il viaggio non è ancora iniziato'}</b><div class="muted">Le spese seguono la data del pagamento.</div></div><div class="list">${dayList(t).map((d,i)=>dayCard(t,d,i+1)).join('')}</div>`,'daysPage')}
function dayCard(t,d,i){const spent=daySpent(t,d),target=t.daily,future=dateObj(d)>dateObj(effectiveToday(t)),cum=t.daily*Math.min(i,elapsed(t))-t.movements.filter(m=>m.type==='expense'&&m.inBudget!==false&&m.paymentDate<=d).reduce((a,m)=>a+m.budgetValue,0);return `<button class="card daycard" onclick="dayDetail('${d}')"><div class="sectionhead"><b>Giorno ${i} — ${fmtDate(d)}</b><span class="pill">${future?'Futuro':fmtBudget(t,spent)}</span></div><div class="daynums"><span>Budget ${fmtBudget(t,target)}</span><span class="${spent>target?'neg':''}">${spent<=target?'Sotto':'Sopra'} ${fmtBudget(t,Math.abs(target-spent))}</span></div><div class="muted">Margine cumulativo: ${cum>=0?'+':''}${fmtBudget(t,cum)} · ${t.movements.filter(m=>m.type==='expense'&&m.inBudget!==false&&m.paymentDate===d).length} spese</div></button>`}
function dayDetail(d){const t=trip(),ms=t.movements.filter(m=>m.type==='expense'&&m.inBudget!==false&&m.paymentDate===d),spent=ms.reduce((a,m)=>a+m.budgetValue,0);layout(`<button class="back" onclick="daysPage()">← Giorni</button><h1>${fmtDate(d)}</h1><div class="grid"><div class="stat"><span class="label">Speso</span><b>${fmtBudget(t,spent)}</b></div><div class="stat"><span class="label">Budget</span><b>${fmtBudget(t,t.daily)}</b></div></div><div class="card"><b>Spese</b>${ms.length?`<div class="list">${ms.map(m=>movementHTML(t,m)).join('')}</div>`:'<div class="empty">Nessuna spesa</div>'}</div>`,'daysPage')}
function statistics(){const t=trip(),s=stats(t),cats=CATS.map(c=>[c[0],t.movements.filter(m=>m.type==='expense'&&m.inBudget!==false&&m.category===c[0]).reduce((a,m)=>a+Number(m.budgetValue||0),0)]).filter(x=>x[1]>0).sort((a,b)=>b[1]-a[1]),total=cats.reduce((a,x)=>a+x[1],0);layout(`<div class="top"><div><div class="sub">ANALISI</div><div class="title">Statistiche</div></div></div><div class="card"><div class="charttitle">Spesa giornaliera</div><div class="legend"><span><i class="solid"></i>Spesa</span><span><i class="dash"></i>Budget giornaliero</span></div>${dailyChart(t)}<p class="chartdesc">Mostra quanto hai speso ogni giorno rispetto al budget giornaliero impostato di ${fmtBudget(t,t.daily)}.</p></div><div class="card"><div class="charttitle">Spese per categoria</div>${cats.length?`<div class="bars">${cats.map(([c,v])=>`<div><span>${esc(c)}</span><div class="bar"><i style="width:${total?v/total*100:0}%"></i></div><b>${fmtBudget(t,v)}</b></div>`).join('')}</div><p class="chartdesc">${esc(cats[0][0])} rappresenta ${total?(cats[0][1]/total*100).toFixed(0):0}% delle spese incluse nel budget.</p>`:'<div class="empty">Nessuna spesa ancora.</div>'}</div><div class="card"><div class="charttitle">Budget cumulativo</div><div class="legend"><span><i class="solid"></i>Spesa cumulativa</span><span><i class="dash"></i>Target cumulativo</span></div>${cumulativeChart(t)}<p class="chartdesc">Il target cumulativo è quanto avresti previsto di spendere fino a quel giorno. La spesa cumulativa è quanto hai realmente speso.</p></div><div class="grid"><div class="stat"><span class="label">Budget residuo</span><b>${fmtBudget(t,s.remaining)}</b></div><div class="stat"><span class="label">Speso durante il viaggio</span><b>${fmtBudget(t,s.spent)}</b></div><div class="stat"><span class="label">Spese pre-viaggio</span><b>${money(s.pre,'EUR')}</b></div><div class="stat"><span class="label">Costo totale finora</span><b>${money(s.spent+s.pre,'EUR')}</b></div></div><div class="card"><div class="charttitle">Commissioni cambi</div>${commissionStats(t)}</div>`,'statistics')}
function commissionInfo(t,m){const from=walletById(t,m.walletFrom),to=walletById(t,m.walletTo),cost=Number(m.eur||0);if(!from||!to||cost<=0)return null;let fee=0,localWallet=null;if(from.currency===t.baseCurrency){fee=cost-Number(m.fromAmount||0);localWallet=to.currency===t.baseCurrency?from:to}else if(to.currency===t.baseCurrency){fee=cost-Number(m.toAmount||0);localWallet=from}else return null;fee=Math.max(0,fee);return fee>0?{fee,wallet:localWallet}:null}
function commissionStats(t){const rows={};t.movements.filter(m=>m.type==='transfer').forEach(m=>{const info=commissionInfo(t,m);if(!info)return;const key=info.wallet.id;rows[key]=(rows[key]||{name:info.wallet.name,currency:info.wallet.currency,total:0});rows[key].total+=info.fee});const vals=Object.values(rows),total=vals.reduce((a,r)=>a+r.total,0);if(!vals.length)return '<div class="empty">Nessuna commissione rilevabile.</div>';return `<div class="grid commission-grid"><div class="stat"><span class="label">Totale commissioni</span><b>${money(total,'EUR')}</b></div></div><div class="list">${vals.sort((a,b)=>b.total-a.total).map(r=>`<div class="item"><div><div class="cat">${esc(r.name)}</div><div class="muted">${esc(r.currency)}</div></div><div class="amount">${money(r.total,'EUR')}</div></div>`).join('')}</div><p class="hint">Le commissioni sono sempre espresse in EUR e raggruppate per portafoglio in valuta locale.</p>`}
function chartBase(t){const days=dayList(t).filter(d=>dateObj(d)<=dateObj(effectiveToday(t)));return{days:days.length?days:[t.start]}}
function chartTicks(max){const step=max/4;return [0,step,step*2,step*3,max]}
function dailyChart(t){const {days}=chartBase(t),vals=days.map(d=>daySpent(t,d)),max=Math.max(t.daily*1.25,...vals,1),w=500,h=220,pL=58,pR=18,pT=12,pB=32,x=i=>pL+i*(w-pL-pR)/Math.max(days.length-1,1),y=v=>h-pB-(v/max)*(h-pT-pB),ticks=chartTicks(max);return `<svg class="chart" viewBox="0 0 ${w} ${h}" role="img">${ticks.map(v=>`<line x1="${pL}" y1="${y(v)}" x2="${w-pR}" y2="${y(v)}" class="chartgrid"/><text x="${pL-7}" y="${y(v)+4}" text-anchor="end" class="charttext">${esc(fmtBudget(t,v))}</text>`).join('')}<line x1="${pL}" y1="${y(t.daily)}" x2="${w-pR}" y2="${y(t.daily)}" class="chartdash"/><polyline points="${vals.map((v,i)=>`${x(i)},${y(v)}`).join(' ')}" class="chartline"/><g>${vals.map((v,i)=>`<circle cx="${x(i)}" cy="${y(v)}" r="3.5" class="chartpoint"/><text x="${x(i)}" y="${h-9}" text-anchor="middle" class="charttext">${fmtDate(days[i]).slice(0,5)}</text>`).join('')}</g></svg>`}
function cumulativeChart(t){const {days}=chartBase(t),actual=days.map(d=>t.movements.filter(m=>m.type==='expense'&&m.inBudget!==false&&m.paymentDate<=d).reduce((a,m)=>a+Number(m.budgetValue||0),0)),target=days.map((d,i)=>t.daily*(i+1)),max=Math.max(...actual,...target,1),w=500,h=220,pL=58,pR=18,pT=12,pB=32,x=i=>pL+i*(w-pL-pR)/Math.max(days.length-1,1),y=v=>h-pB-(v/max)*(h-pT-pB),ticks=chartTicks(max);return `<svg class="chart" viewBox="0 0 ${w} ${h}" role="img">${ticks.map(v=>`<line x1="${pL}" y1="${y(v)}" x2="${w-pR}" y2="${y(v)}" class="chartgrid"/><text x="${pL-7}" y="${y(v)+4}" text-anchor="end" class="charttext">${esc(fmtBudget(t,v))}</text>`).join('')}<polyline points="${target.map((v,i)=>`${x(i)},${y(v)}`).join(' ')}" class="chartdash"/><polyline points="${actual.map((v,i)=>`${x(i)},${y(v)}`).join(' ')}" class="chartline"/>${days.map((d,i)=>`<circle cx="${x(i)}" cy="${y(actual[i])}" r="3.5" class="chartpoint"/><circle cx="${x(i)}" cy="${y(target[i])}" r="3.5" class="charttarget"/><text x="${x(i)}" y="${h-9}" text-anchor="middle" class="charttext">${fmtDate(d).slice(0,5)}</text>`).join('')}</svg>`}
function settings(){const t=trip();layout(`<div class="top"><div><div class="sub">VIAGGIO</div><div class="title">Impostazioni</div></div></div><div class="card"><div class="field"><label>Nome viaggio</label><input id="sname" value="${esc(t.name)}"></div><div class="field"><label>Valuta del budget</label><select id="sbase">${currencyOptions(t.baseCurrency)}</select></div><div class="field"><label>Budget totale</label><input id="sbudget" inputmode="decimal" type="text" value="${t.budget}"></div><div class="field"><label>Budget giornaliero</label><input id="sdaily" inputmode="decimal" type="text" value="${t.daily}"></div><div class="field"><label>Data di inizio</label><input id="sstart" type="date" value="${t.start}"></div><button class="btn full" onclick="saveSettings()">Salva modifiche</button></div><div class="card"><div class="sectionhead"><b>Modalità test</b><span class="pill">${t.testMode?'ATTIVA':'OFF'}</span></div><div class="field"><label><input id="testMode" type="checkbox" ${t.testMode?'checked':''}> Usa una data simulata</label></div><div class="field"><label>Data simulata</label><input id="testDate" type="date" value="${esc(t.testDate||t.start)}"></div><div class="row"><button class="btn secondary" onclick="shiftTest(-1)">← Giorno</button><button class="btn secondary" onclick="shiftTest(1)">Giorno →</button></div><button class="btn full mt" onclick="saveTestMode()">Applica modalità test</button></div><div class="card backup-card"><b>Backup e dati</b><div class="backup-actions"><button class="btn secondary full" onclick="exportData()">Esporta backup completo</button><button class="btn secondary full" onclick="importData('replace')">Sostituisci con backup</button><button class="btn secondary full" onclick="importData('merge')">Aggiungi da backup</button></div><p class="hint">Il backup contiene tutti i viaggi, movimenti, portafogli e impostazioni.</p></div><div class="card"><button class="btn dangerbtn full" onclick="deleteTrip()">Elimina viaggio</button></div>`,'settings')}
function saveSettings(){const t=trip();t.name=document.getElementById('sname').value.trim()||t.name;t.baseCurrency=document.getElementById('sbase').value||t.baseCurrency;t.budget=Math.max(0,parseAmount(document.getElementById('sbudget').value));t.daily=Math.max(0,parseAmount(document.getElementById('sdaily').value));t.start=document.getElementById('sstart').value||t.start;save();renderCurrent('settings')}
function saveTestMode(){const t=trip();t.testMode=document.getElementById('testMode').checked;t.testDate=document.getElementById('testDate').value||t.start;save();renderCurrent('settings')}
function shiftTest(delta){const e=document.getElementById('testDate');const d=dateObj(e?.value||trip().testDate||trip().start);d.setDate(d.getDate()+delta);if(e)e.value=isoDate(d);document.getElementById('testMode').checked=true}
function deleteTrip(){const t=trip();if(prompt(`Per eliminare definitivamente "${t.name}", scrivi ELIMINA`)!=='ELIMINA')return;data.trips=data.trips.filter(x=>x.id!==t.id);data.active=data.trips[0]?.id||null;save();home()}
function exportData(){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='travel-budget-backup-completo.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function importData(mode){const input=document.createElement('input');input.type='file';input.accept='.json,application/json';input.onchange=()=>{const f=input.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const incoming=JSON.parse(r.result);if(!Array.isArray(incoming.trips))throw new Error();if(mode==='replace'){if(!confirm('Sostituire tutti i dati attuali con il backup?'))return;data=incoming;migrate()}else{if(!confirm('Aggiungere i viaggi del backup a quelli attuali?'))return;const ids=new Set(data.trips.map(t=>t.id));incoming.trips.forEach(t=>{if(ids.has(t.id))t.id=id();data.trips.push(t)});migrate()}if(!data.active&&data.trips[0])data.active=data.trips[0].id;save();render()}catch(e){alert('Backup non valido.')}};r.readAsText(f)};input.click()}
function render(){if(!data.trips.length)return home();if(!trip())data.active=data.trips[0].id;dashboard()}
if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js');
render();
